# Generated by Django 4.0.6 on 2022-08-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=2)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
